### ISSUE TITLE
malfunction after installing plugin

### ISSUE THREAD

**Issue by Hoffenbar** [JackGruber/joplin-plugin-copytags#2]
Hello, after installing the plugin yesterday into the latest available Joplin release, Joplin would not start properly anymore. The title screen appears, some menues are choosable but after clickling this and that, errors appear. Unfortunally, I dion't safe the error informationen that appear at some time in the main window. Maybere there´s some conflict with some other plugins; many of them are active.... I'm on Windows 10, using joplin portable.

![image](https://user-images.githubusercontent.com/46227007/209436873-9228670c-914b-40ff-87e6-cb7c263ff6b2.png)
![image](https://user-images.githubusercontent.com/46227007/209436877-5d7308f7-17ef-4279-9b96-c31150f872c2.png)

Joplin 2.9.17 (prod, win32)

Client-ID: ef58bde158c94e218c1c2af31a3e3966
Sync-Version: 3
Profil-Version: 41
Unterstützter Schlüsselbund: Nein

Revision: a84a8e7

**Comment by JackGruber** [comment]
>Unfortunally, I dion't safe the error informationen that appear at some time in the main window.

Without accurate error message logs it is almost impossible to help

>Maybere there´s some conflict with some other plugins

I don't believe that to 99%

If you have the error message and log files, you can see where the error is coming from and report an exact error here, to Joplin directly or to the associated plugin. I will close this error, as it is not repeatable. Feel free to open a new Issue with more details.
