### ISSUE TITLE
Small typo, "assignt" in screenshot

### ISSUE THREAD

**Issue by NGenetzky** [JackGruber/joplin-plugin-copytags#3]
I believe you meant to say "assigned" instead of "assignt".

Screenshot seen on this page: https://joplinapp.org/plugins/plugin/io.github.jackgruber.copytags/?from-tab=home

I was unable to easily locate this in the code, and if it's already been fixed feel to close (if you don't want to update the screenshot).

**Comment by JackGruber** [comment]
Oh I was searching in the source code, but the typo is in the record / screenshot tagging_dialog.jpg and main_tagging.gif 
Thanks for reporting, will be fixed.
